Default parameter error surface blending service 11
tecnalia-advancedmanufacturing-robotics/godel pull request #4
Opened 2020-03-10 14:11 UTC by pdaelm

Fix to get path planning parameters from ros param server if parameters defined in GUI are not coherent, and `~/.ros/godel_*.msg` files are missing.

2020-03-10 15:16 UTC, miguelprada commented
I can confirm this works in my limited trials.

It would be even better if this populated the option menus in the GUI with the defaults read from the parameter server as well. Do you think this is feasible or would it complicate things too much?

2020-03-10 15:40 UTC, pdaelm commented
I can try to do it, I let you know

2020-03-12 11:38 UTC, miguelprada requested changes
Other than the inline comments, I tested it and it seems to work as expected.

2020-03-12 11:38 UTC, miguelprada commented on godel_surface_detection/src/services/surface_blending_service.cpp
> +  ros::NodeHandle nh ("path_planning_params");
Other parameter _sets_ are read from specific namespaces (e.g. [`"~/blend_plan"`](https://github.com/tecnalia-advancedmanufacturing-robotics/godel/blob/94a63a2ad693f3d7941fe35584b481da4080ae47/godel_surface_detection/src/services/surface_blending_service.cpp#L225)). Shouldn't this be done similarly?

2020-03-12 11:38 UTC, miguelprada commented on godel_surface_detection/src/services/surface_blending_service.cpp
> +          loadParam(nh, "tool_radius", path_planning_params_.tool_radius);
If any of the `loadParam` call fails the [remaining parameters will not be loaded](https://en.wikipedia.org/wiki/Short-circuit_evaluation), yet [only a warning is raised](https://github.com/tecnalia-advancedmanufacturing-robotics/godel/blob/94a63a2ad693f3d7941fe35584b481da4080ae47/godel_surface_detection/src/services/surface_blending_service.cpp#L94-L95) and initialization continues. This doesn't make a lot of sense to me.

At the very least I think we should always try to read all parameters.

2020-04-06 09:40 UTC, pdaelm commented
Ping

2020-05-13 08:18 UTC, merged